name: Daily System Monitor

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run monitor script
        run: |
          chmod +x monitor.sh
          ./monitor.sh

      - name: Upload log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: monitor-log
          path: logs/*.log
