name: Daily System Monitor

on:
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug: list all files
        run: |
          ls -la
          find .

      - name: Run monitor script with bash
        run: bash monitor.sh

      - name: Upload log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: monitor-log
          path: logs/*.log
