name: Daily System Monitor

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List files (debug)
        run: ls -la

      - name: Run monitor.sh with bash
        run: bash monitor.sh

      - name: Upload log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: monitor-log
          path: logs/*.log
